### ISSUE TITLE
Doesn't work on multi display

### ISSUE THREAD

**Issue by Zillion01** [rsayfutdinov/Pikka#12]
Pikka does not work on external monitors, connected to Macbook.

**Comment by rsayfutdinov** [comment]
> Pikka does not work on external monitors, connected to Macbook.

Hi,

Please make sure that you have updated to the latest version.
This issue should be resolved with v. 2.3.3

Regards,
Ruslan.

**Comment by rsayfutdinov** [comment]
> Pikka does not work on external monitors, connected to Macbook.

See https://github.com/rsayfutdinov/Pikka/issues/11

**Comment by Zillion01** [comment]
Maybe put the version number somewhere?

According to the app store it's 2.3.2 not 2.3.3? However seems to work now. thx

**Comment by rsayfutdinov** [comment]
> Maybe put the version number somewhere?
> 
> According to the app store it's 2.3.2 not 2.3.3? However seems to work now. thx

Yeah, I meant 2.3.3.
Will add the number version within the next release.
