### ISSUE TITLE
Very light grey gets sampled as Very light Pink

### ISSUE THREAD

**Issue by Zillion01** [rsayfutdinov/Pikka#13]
Color name wrong for #f0f0f0. Pikka says it's Very light Pink. See attachment

<img width="70" alt="Schermafbeelding 2021-07-01 om 17 21 56" src="https://user-images.githubusercontent.com/1055822/124149696-22916880-da91-11eb-977c-12990a0fbbc8.png">

**Comment by rsayfutdinov** [comment]
That’s definitely wrong:)
