### ISSUE TITLE
UIColor RGB uses wrong format

### ISSUE THREAD

**Issue by vanwijkdave** [rsayfutdinov/Pikka#14]
Hey, I've been using Pikka for some time now, love it!

A small suggestion is that Pikka uses this format for UIColor-RGB,  [UIColor colorWithRed:x green:x blue:x alpha:x), but it should end with a ] instead of a ).

See screenshot for example ⤵️
<img width="439" alt="image" src="https://user-images.githubusercontent.com/31007683/124273950-f0d7da80-db40-11eb-83ca-a45e4fd4705c.png">

Thanks!

**Comment by rsayfutdinov** [comment]
> Hey, I've been using Pikka for some time now, love it!
> 
> 
> 
> A small suggestion is that Pikka uses this format for UIColor-RGB,  [UIColor colorWithRed:x green:x blue:x alpha:x), but it should end with a ] instead of a ).
> 
> 
> 
> See screenshot for example ⤵️
> 
> <img width="439" alt="image" src="https://user-images.githubusercontent.com/31007683/124273950-f0d7da80-db40-11eb-83ca-a45e4fd4705c.png">
> 
> 
> 
> Thanks!
> 
> 

Thanks! Will fix it within next release.

Regards,
Ruslan

**Comment by rsayfutdinov** [comment]
Fixed with 2.3.3. (Will be released soon)
