### ISSUE TITLE
Purchased via App Store on MacBook, but Unable to Recognize Purchase on Mac Mini

### ISSUE THREAD

**Issue by ryschram** [rsayfutdinov/Pikka#54]
I've used the same App Store account and downloaded the app on both machines. Purchaesd Pikka on Macbook, but Mac Mini still has 'Get Pikaa Pro...' in menu. I've tried uninstalling and reinstalling, but this doesn't work. How do I authenticate for the second machine?

**Comment by rsayfutdinov** [comment]
You can click on the Purchase button again. This will restore your previous purchase and you will not be charged again. Please make sure you log in with the same Apple ID in AppStore.  

PS: I will add the "Restore purchases" option to the next release.

**Comment by ryschram** [comment]
Excellent, I will do this. Thank you for the quick response!
